import { Show } from "solid-js";
import advice from "../advice.json";

/**
 * Displays the daily accountability summary generated by bin/copilot-summary.ts.
 * Content is sourced from src/advice.json, which is regenerated daily by CI.
 * Renders nothing if the file has not yet been populated.
 */
export default function DailyAdvice() {
  const hasContent =
    advice.headline.length > 0 &&
    advice.summary.length > 0 &&
    advice.details.length > 0;

  return (
    <Show when={hasContent}>
      <div class="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 space-y-3">
        <p class="text-xs font-medium uppercase tracking-widest text-[var(--color-text-muted)]">
          Today's Focus
        </p>
        <h2 class="text-lg font-semibold text-[var(--color-text)]">
          {advice.headline}
        </h2>
        <p class="text-sm font-medium text-[var(--color-text)]">
          {advice.summary}
        </p>
        <p class="text-sm text-[var(--color-text-muted)] leading-relaxed">
          {advice.details}
        </p>
      </div>
    </Show>
  );
}
