name: Fetch and Append Data to SQLite (Bun)

on:
  schedule:
    - cron: '35 8 * * *' # Run once per day
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write  # We want to push updates to the db

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2

    - name: Fetch CSV data from API and update SQLite DB
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: bun run ./fetch-weight.ts

    - name: Commit changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add data.db
        git commit -m "Append new data to SQLite database"
        git push
